"use client"

import React from "react"

export interface AnalyticsReportProps {
  data: {
    sentiment: any
    topThreats: any[]
  }
  range: "today" | "week"
}

export const AnalyticsReport = React.forwardRef<HTMLDivElement, AnalyticsReportProps>(
  ({ data, range }, ref) => {
    return (
      <div
        ref={ref}
        className="p-10 bg-white text-black w-[900px] font-sans"
      >
        {/* HEADER */}
        <h1 className="text-3xl font-bold">Konfam Analytics Report</h1>
        <p className="text-gray-600 mb-6 text-sm">
          {range === "today" ? "Today’s Report" : "This Week’s Report"}
        </p>

        <hr className="my-6" />

        {/* EXEC SUMMARY */}
        <h2 className="text-xl font-semibold mb-2">Executive Summary</h2>

        <p className="text-sm leading-relaxed">
          This intelligence report summarizes the reputation signals, sentiment
          movement, and threat detection insights captured during the monitoring
          period.
        </p>


        {/* TOP THREATS */}
        <h2 className="text-lg font-semibold mt-10 mb-3">Top Threats</h2>

        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className="border-b bg-gray-100">
              <th className="p-2 text-left">Threat</th>
              <th className="p-2 text-left">Severity</th>
              <th className="p-2 text-left">Impact Score</th>
            </tr>
          </thead>

          <tbody>
            {data.topThreats.map((t, index) => (
              <tr key={index} className="border-b">
                <td className="p-2">{t.content}</td>
                <td className="p-2">{t.severity}</td>
                <td className="p-2">{t.sentimentImpact}</td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* FOOTER */}
        <footer className="mt-12 text-xs text-gray-400">
          Generated by Konfam • {new Date().toLocaleString()}
        </footer>
      </div>
    )
  }
)

AnalyticsReport.displayName = "AnalyticsReport"
