import { jsPDF } from "jspdf"
import Chart from "chart.js/auto"
import { mockSentimentData, mockThreats } from "@/lib/demo-data"

export async function generateAnalyticsPDF(range: "today" | "week") {
  const doc = new jsPDF("p", "mm", "a4")

  // --------------------------------------------
  // HEADER
  // --------------------------------------------
  doc.setFontSize(22)
  doc.text("Konfam Analytics Report", 14, 20)

  doc.setFontSize(12)
  doc.text(
    range === "today" ? "Daily Report" : "Weekly Report",
    14,
    28
  )

  // --------------------------------------------
  // KPI SUMMARY
  // --------------------------------------------
  const totalThreats = mockThreats.length
  const critical = mockThreats.filter((t) => t.severity === "CRITICAL").length
  const high = mockThreats.filter((t) => t.severity === "HIGH").length

  doc.setFontSize(14)
  doc.text("Summary", 14, 40)

  doc.setFontSize(11)
  doc.text(`Total Threats: ${totalThreats}`, 14, 48)
  doc.text(`Critical Threats: ${critical}`, 14, 54)
  doc.text(`High Severity: ${high}`, 14, 60)

  // --------------------------------------------
  // SENTIMENT CHART (canvas in memory)
  // --------------------------------------------
  const sentimentCanvas = document.createElement("canvas")
  sentimentCanvas.width = 800
  sentimentCanvas.height = 300
  const ctx1 = sentimentCanvas.getContext("2d")!

  new Chart(ctx1, {
    type: "line",
    data: {
      labels: mockSentimentData.map((x) => x.time),
      datasets: [
        {
          label: "Sentiment Score",
          data: mockSentimentData.map((x) => x.score),
          borderColor: "#2563eb",
          borderWidth: 2,
          tension: 0.3,
        },
      ],
    },
    options: { responsive: false },
  })

  await new Promise((r) => setTimeout(r, 300))
  const sentimentImg = sentimentCanvas.toDataURL("image/png")

  doc.addImage(sentimentImg, "PNG", 14, 70, 180, 60)

  // --------------------------------------------
  // THREAT SEVERITY CHART
  // --------------------------------------------
  const severityCanvas = document.createElement("canvas")
  severityCanvas.width = 800
  severityCanvas.height = 300
  const ctx2 = severityCanvas.getContext("2d")!

  const severityCounts = {
    CRITICAL: mockThreats.filter((t) => t.severity === "CRITICAL").length,
    HIGH: mockThreats.filter((t) => t.severity === "HIGH").length,
    MEDIUM: mockThreats.filter((t) => t.severity === "MEDIUM").length,
    LOW: mockThreats.filter((t) => t.severity === "LOW").length,
  }

  new Chart(ctx2, {
    type: "bar",
    data: {
      labels: ["Critical", "High", "Medium", "Low"],
      datasets: [
        {
          label: "Threat Count",
          data: [
            severityCounts.CRITICAL,
            severityCounts.HIGH,
            severityCounts.MEDIUM,
            severityCounts.LOW,
          ],
          backgroundColor: ["#dc2626", "#ea580c", "#facc15", "#16a34a"],
        },
      ],
    },
    options: { responsive: false },
  })

  await new Promise((r) => setTimeout(r, 300))
  const severityImg = severityCanvas.toDataURL("image/png")

  doc.addImage(severityImg, "PNG", 14, 140, 180, 60)

  // --------------------------------------------
  // TOP THREATS TABLE
  // --------------------------------------------
  doc.addPage()
  doc.setFontSize(16)
  doc.text("Top Threats", 14, 20)

  doc.setFontSize(10)
  let y = 30
  mockThreats.slice(0, 6).forEach((t) => {
    doc.text(`• ${t.content}`, 14, y)
    doc.text(`Severity: ${t.severity}`, 160, y)
    y += 10
  })

  // --------------------------------------------
  // FOOTER
  // --------------------------------------------
  doc.setFontSize(8)
  doc.text(
    `Generated by Konfam • ${new Date().toLocaleString()}`,
    14,
    285
  )

  return doc.save(
    range === "today" ? "konfam-daily-report.pdf" : "konfam-weekly-report.pdf"
  )
}
